services:
  - type: pserv
    name: rusttaskflow-db
    env: postgresql
    plan: free
    databaseName: rusttaskflow
    user: rusttaskflow_user

  - type: web
    name: rusttaskflow-backend
    env: rust
    rootDir: rusttaskflow-web
    buildCommand: cargo build --release --bin rusttaskflow-server
    startCommand: ./target/release/rusttaskflow-server
    envVars:
      - key: RUST_LOG
        value: debug
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://jimmyramsamynaick.github.io
      - key: DATABASE_URL
        fromDatabase:
          name: rusttaskflow-db
          property: connectionString